# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
after_success:
# push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BibTeX")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'


jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - export DOCUMENTER_DEBUG="true"
        - julia --color=yes --project=docs/ -e 'using Pkg;
                                                      Pkg.instantiate();
                                                      Pkg.develop(PackageSpec(path=pwd()));
                                                      Pkg.build("BibTeX")'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
