name = "BibTeX"
uuid = "7b0aa2c9-049f-5cec-894a-2b6b781bb25e"
version = "0.0.0"

[compat]
julia = "≥ 0.7.0"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Documenter"]
